### ISSUE TITLE
Problems uploading media

### ISSUE THREAD

**Issue by felix-wo** [eerotal/LibreSignage#27]
Getting problems uploading media files:

- Doesn’t accept file names with blankspace.
- Trying to upload a file (without blankspace in its name) fails, get red button "Upload failed. Retry?" (Cecked upload_max_filesize in php.ini against the size of my picture.)
- With a self created slide (user "admin") the window "Add media" says "The maximum number of files for this slide has been reached. You can't upload more files." There are no files yet attached to this slide though.

Thanks!

**Comment by eerotal** [comment]
* I'll have to write a fix for the whitespace problem. That should be quite simple so I'll include it in the next patch release.
* It sounds like there's still some sort of a configuration problem with the PHP file uploading system. There are a few PHP settings that need to be changed for file uploading to work. Below are some example values that work, but they set quite loose limits on file size so you may want to modify them according to your needs. Anyway, please try these and report back.
```
file_uploads = On
upload_max_filesize = 200M
max_file_uploads = 20
post_max_size = 210M
memory_limit = 300M
```
* I fixed this in f04ed356de6eab43ee6e031db6ff1e73b18b4d52 in the `next` and `v0.2.2-dev` branches. The fix will be included in the next patch release, but you can test it by doing a `git pull` in the `v0.2.2-dev` branch.

**Comment by felix-wo** [comment]
Thank you, I appreciate your efforts!

No luck yet uploading media, same error with the red button. Took the values for php.ini from your post before. Tried just a little .jpg of <70 kb.

Also still not able to even choose a media file for a self-created slide, same error as mentioned ("The maximum number of files for this slide has been reached. You can't upload more files."). Should be on branch v0.2.2-dev, just updated. (Webinterface says: "LibreSignage v0.2.1-11-g5de124d-dirty"; is that correct?)

**Comment by eerotal** [comment]
That's odd. Could you rebuild the LibreSignage installation but enable debugging when `make configure` asks for it. Then open the network monitoring tab of your browser's developer tools while you're in the web interface and try to upload a file. There should be a call to `slide_upload_asset.php`. Please paste the response of that call here so I can debug it.

The `-dirty` suffix in the version number might indicate there's something off with the sources. When updating did you run all of the commands below, especially `make clean` and `make`? My fix did work on my own system but there might still be other problems too of course.

```
git pull
make clean
make
sudo make install
```

**Comment by felix-wo** [comment]
Yes, I did all these commands to update via git. I’ve just even deleted my LibreSignage directory completely, then a fresh `git pull`, and `git checkout v0.2.2-dev` before the `make configure`. Obviously though, I’m still not on the right version. Your new font tag doesn’t work either (editor drops error ">> Unknown tag: font (@ 7:4)"). Can’t see what I’m doing wrong …

**Comment by eerotal** [comment]
Oh, I think I know what's wrong. Your browser is probably loading a cached old version of the JavaScript. You can force a reload by pressing CTRL+F5 in your browser and then check whether the font tag works.

If *even that* doesn't fix all of the problems, you could try deleting the whole LibreSignage install directory from `/var/www/<domain>`. Then you can re-clone the LibreSignage repo and do the whole setup again.

**Comment by felix-wo** [comment]
Aah, now I've got it. (New font tag works.) Normally I check with a "private" (Firofox) or "incognito" (Chromium) browser window for that reason (caching), but this time I missed to do so – I’m sorry!

But file upload still doesn’t work. So here’s the response to `slide_upload_asset.php` as requested:

> {"error":1,"thrown_at":"\/var\/www\/libresignage.my.lan\/common\/php\/thumbnail\/imgthumb.php @ ln: 59","e_msg":"Class 'ConfigException' not found","e_trace":"#0 \/var\/www\/libresignage.my.lan\/common\/php\/thumbnail\/thumbnail.php(35): gen_img_thumb('\/var\/www\/libres...', '\/var\/www\/libres...', 320, 180)\n#1 \/var\/www\/libresignage.my.lan\/common\/php\/slide\/slideasset.php(93): generate_thumbnail('\/var\/www\/libres...', '\/var\/www\/libres...', 320, 180)\n#2 \/var\/www\/libresignage.my.lan\/common\/php\/slide\/slide.php(401): SlideAsset->new(Array, '\/var\/www\/libres...')\n#3 \/var\/www\/libresignage.my.lan\/api\/endpoint\/slide\/asset\/slide_upload_asset.php(92): Slide->store_uploaded_asset(Array)\n#4 {main}"}

(Domain name anonymized.)

**Comment by eerotal** [comment]
I also just fixed the problem where the media uploader didn't accept filenames that had spaces in them. Could you check that all of the bugs you found have now been fixed and report back?

**Comment by felix-wo** [comment]
Great!

- File upload works now. Embedding works, videos do play.
- Image thumbnails work after installing package `php7.0-gd` (on Debian Stretch) and `phpenmod -v7.0 gd`, as you said.
- Video thumbnails work after installing `ffmpeg` and enabling them in `common/php/config.php` of the LibreSignage instance.
- The "odd closing behaviour" of the "Add media" window is fixed, indeed.
- It now accepts file names with spaces. (Btw, it doesn’t accept file names containing ":" – a non Windows problem, and even there not really one …)

Problems/flaws:

- Where thumbnails are not enabled, it shows a "broken media" icon.
- Videos which had already been added at the time of activating video thumbnails remain showing the "broken media" icon.
- Duplicate a slide with media, then delete original slide => Even when actualizing the media to the link the duplicate slide offers under its "Add media" window, the image remains broken.

Further concerns:

- I appreciate the simplicity of the markup for the slides, but for my view – spoken from a user’s perspective – there’s a lack of possibilities for some typical design cases which would make the application useful in production. I have a bunch of ideas for enhancements in this field? Do you have interest that I unfold these (in a separate posting)?

**Comment by eerotal** [comment]
Great!

* The broken media icon thing is something that's on my TODO list.
* Generating thumbnails for files uploaded before thumbnails were enabled should be quite easy. I'll have to look into it sometime.
* Making files system-wide might be a better approach indeed.

By all means, tell me how I could improve the markup. Although I have also considered implementing a way to create slides with HTML and CSS for users that need more advanced functionality.

**Comment by felix-wo** [comment]
Fine, sounds all promising to me. I’m going to reach out to you again …

**Comment by eerotal** [comment]
I'll close this as I separated the problems not yet solved into issues #32 and #33 to make tracking them easier.
